// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD33-iHoQm7UrdLDrRpUidjvT-kjuX0Tgc',
    appId: '1:135647957737:web:790606abd97da973e9d678',
    messagingSenderId: '135647957737',
    projectId: 'my-portfolio-648ab',
    authDomain: 'my-portfolio-648ab.firebaseapp.com',
    storageBucket: 'my-portfolio-648ab.appspot.com',
    measurementId: 'G-WR9B923BTR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAO0Dyez6u1W3HjJlHwW9ad_cZfM5rnEQw',
    appId: '1:135647957737:android:2d50b4dae2dd2dfee9d678',
    messagingSenderId: '135647957737',
    projectId: 'my-portfolio-648ab',
    storageBucket: 'my-portfolio-648ab.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcWmZrrlTKxxgfPh5KZVum1cIGZ6I6B44',
    appId: '1:135647957737:ios:cce784b2e2805cace9d678',
    messagingSenderId: '135647957737',
    projectId: 'my-portfolio-648ab',
    storageBucket: 'my-portfolio-648ab.appspot.com',
    iosClientId: '135647957737-751bgp0ji1r4cs2im858g8l530p6rlm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myportfolio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcWmZrrlTKxxgfPh5KZVum1cIGZ6I6B44',
    appId: '1:135647957737:ios:cce784b2e2805cace9d678',
    messagingSenderId: '135647957737',
    projectId: 'my-portfolio-648ab',
    storageBucket: 'my-portfolio-648ab.appspot.com',
    iosClientId: '135647957737-751bgp0ji1r4cs2im858g8l530p6rlm3.apps.googleusercontent.com',
    iosBundleId: 'com.example.myportfolio',
  );
}
